name: Generate PDF from README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Install pdflatex
      run: sudo apt-get install -y texlive-latex-base

    - name: Convert README.md to PDF
      run: pandoc README.md -o README.pdf --pdf-engine=pdflatex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: README-pdf
        path: README.pdf
