name: Convert README to PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Install LaTeX
      run: sudo apt-get install -y texlive

    - name: Convert README.md to README.pdf
      run: pandoc README.md -o README.pdf --resource-path=.:assets

    - name: Upload README.pdf
      uses: actions/upload-artifact@v2
      with:
        name: README-pdf
        path: README.pdf